;베이스 수치 (수정 금지)
[READONLY]
front_pixel_distance_base=200
side_pixel_distance_base=200

;캠 설정
[CAMERA]
front_camera_id=0
side_camera_id=2

resolution_width=1280
resolution_height=720

front_pixel_distance=212
side_pixel_distance=207

side_angle_offset=0

;키오스크 앱 기본 설정
[KIOSK]
mirrormode_timeout=300
debugmode_enable=true
mediapipe_Delegate_type=CPU
frame_limit=30

home_lesson_enable=true
home_practice_enable=true
home_aicoaching_enable=true
home_mirror_enable=true
home_range_enable=false
home_studio_enable=true

;어드레스 그립 손목 감지거리
[SWINGCHECK]
address_hand_distance=10
